### ISSUE TITLE
Broom in enchanting table gives no option to enchant

### ISSUE THREAD

**Issue by GraySloth** [EterDelta/Brooms#3]
![image](https://user-images.githubusercontent.com/11801084/143897849-ea47ba70-ff89-4856-baba-39b3697a052d.png)
Not sure if this is intentional or some sort of mod conflict.
I am able to obtain broom enchants on a book in the enchanting table and I am able to apply it to a broom via the anvil.

BroomsMod-1.16.5-1.1.1.jar
forge-36.2.0

[modlist.txt](https://github.com/EterDelta/Brooms/files/7619414/modlist.txt)

**Comment by EterDelta** [comment]
It actually works as intended. The only way to enchant a broom is through books (by enchanting them, trading them or finding them in loot). The project page explains it briefly:
![Screenshot](https://user-images.githubusercontent.com/67644822/143937385-56bca8c4-a3fb-473a-887d-56dd25e13d82.PNG)

**Comment by GraySloth** [comment]
Ah I see, maybe it should mention that enchantments are _only_ obtainable through those secondary methods.

**Comment by EterDelta** [comment]
Yeah, I modified the project page. Thanks for the suggestion.
